name: Build and deploy omnifi-backend to EC2 with CI/CD - omnifi 

on:
  push:
    branches: [master]
    
jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: us-east-1
          aws-access-key-id: AKIAXU3KGQZWO3V5VEOX
          aws-secret-access-key: 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
          instance-ids: i-0dc9e66342a1f8f1a
          comment: Deploy the master branch
          working-directory: /home/ubuntu/omnibackend
          command: /bin/sh ./deploy.sh
          
          # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
